export const guardsList = [
  { id: 1, userAvatar: "", name: "Neco Lewin", hourly: 40.0 },
  { id: 2, userAvatar: "", name: "Ava Mitchell", hourly: 32.5 },
  { id: 3, userAvatar: "", name: "Liam Carter", hourly: 28.75 },
  { id: 4, userAvatar: "", name: "Sophia Ramirez", hourly: 35.0 },
  { id: 5, userAvatar: "", name: "Ethan Patel", hourly: 42.0 },
  { id: 6, userAvatar: "", name: "Maya Johnson", hourly: 30.0 },
  { id: 7, userAvatar: "", name: "Noah Kim", hourly: 38.0 },
  { id: 8, userAvatar: "", name: "Olivia Chen", hourly: 29.5 },
  { id: 9, userAvatar: "", name: "William Scott", hourly: 45.0 },
  { id: 10, userAvatar: "", name: "Isabella Davis", hourly: 34.25 },
  { id: 11, userAvatar: "", name: "James Thompson", hourly: 31.0 },
  { id: 12, userAvatar: "", name: "Mila Anderson", hourly: 36.75 },
  { id: 13, userAvatar: "", name: "Benjamin White", hourly: 27.0 },
  { id: 14, userAvatar: "", name: "Amelia Robinson", hourly: 33.5 },
  { id: 15, userAvatar: "", name: "Lucas Martin", hourly: 41.25 },
  { id: 16, userAvatar: "", name: "Harper Lewis", hourly: 39.0 },
  { id: 17, userAvatar: "", name: "Alexander Walker", hourly: 37.5 },
  { id: 18, userAvatar: "", name: "Charlotte Hall", hourly: 30.75 },
  { id: 19, userAvatar: "", name: "Elijah Young", hourly: 44.0 },
  { id: 20, userAvatar: "", name: "Aria King", hourly: 29.0 },
  { id: 21, userAvatar: "", name: "Henry Brooks", hourly: 34.0 },
  { id: 22, userAvatar: "", name: "Ella Torres", hourly: 31.25 },
  { id: 23, userAvatar: "", name: "Jackson Rivera", hourly: 40.5 },
  { id: 24, userAvatar: "", name: "Scarlett Adams", hourly: 36.0 },
  { id: 25, userAvatar: "", name: "Michael Evans", hourly: 28.0 },
  { id: 26, userAvatar: "", name: "Zoe Murphy", hourly: 32.75 },
  { id: 27, userAvatar: "", name: "Daniel Hughes", hourly: 39.25 },
  { id: 28, userAvatar: "", name: "Grace Foster", hourly: 30.5 },
  { id: 29, userAvatar: "", name: "Matthew Perez", hourly: 42.75 },
  { id: 30, userAvatar: "", name: "Lily Edwards", hourly: 35.25 },
  { id: 31, userAvatar: "", name: "Sebastian Gray", hourly: 38.5 },
  { id: 32, userAvatar: "", name: "Chloe Barnes", hourly: 27.5 },
  { id: 33, userAvatar: "", name: "Jack Murphy", hourly: 44.25 },
  { id: 34, userAvatar: "", name: "Victoria Long", hourly: 29.75 },
  { id: 35, userAvatar: "", name: "Owen Price", hourly: 37.0 },
  { id: 36, userAvatar: "", name: "Madison Hill", hourly: 33.0 },
  { id: 37, userAvatar: "", name: "Carter Cooper", hourly: 41.0 },
  { id: 38, userAvatar: "", name: "Layla Ward", hourly: 30.25 },
  { id: 39, userAvatar: "", name: "Ryan Green", hourly: 43.5 },
  { id: 40, userAvatar: "", name: "Penelope Baker", hourly: 28.25 },
];

export const venuesList = [
  { id: 1, userAvatar: "", name: "Paris Texas", address: '461 King St. West' },
  { id: 2, userAvatar: "", name: "Pizza Wine Disco", address: '788 King St. West' },
  { id: 3, userAvatar: "", name: "National", address: '486 Front St. West' },
  { id: 4, userAvatar: "", name: "Aera", address: '8 Spadina Ave.' },
  { id: 5, userAvatar: "", name: "Cibo King", address: '522 King St. West' },
  { id: 6, userAvatar: "", name: "Blue Bovine", address: '65 Front St. West' }
];

export const usersList = [
  { id: 1, userAvatar: "", name: "Alex Petropoulos", role: 'Admin' },
  { id: 2, userAvatar: "", name: "Cathy da Cunha", role: 'Admin' }
];