import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import MainPanel from "@/components/MainPanel";
import Navigation from "@/components/Navigation";
import Container from "@/components/Container";

const k2d = K2D({
  variable: "--font-k2d",
  display: "swap",
  subsets: ["latin"],
  // keep only the weights you actually use to trim bundle size
  weight: ["400", "500", "600", "700"],
  // style: ["normal","italic"], // uncomment if you need italics
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isLoggedIn = true; // [TODO] replace with NextAuth

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.variable} antialiased text-font-primary bg-gradient-to-tr from-neutral-700 to-neutral-800 flex items-center`}>
        <Container className={`flex items-center w-full h-full gap-8 ${isLoggedIn && '!pr-10'}`}>
          {isLoggedIn && <Navigation />}
          <MainPanel>{children}</MainPanel>
        </Container>
      </body>
    </html>
  );
}
