import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import MainPanel from "@/components/MainPanel";
import Navigation from "@/components/Navigation";
import Container from "@/components/Container";
import { auth } from "../auth";

const k2d = K2D({
  variable: "--font-k2d",
  display: "swap",
  subsets: ["latin"],
  // keep only the weights you actually use to trim bundle size
  weight: ["400", "500", "600", "700"],
  // style: ["normal","italic"], // uncomment if you need italics
});

export const metadata: Metadata = {
  title: "Ironclad Scheduling",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  The session flag to see if user is logged in or not
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${k2d.variable} antialiased text-font-primary overflow-y-hidden`}>
        <Container noStyle className={`flex items-center w-full h-full gap-10 px-10 bg-gradient-to-tr from-neutral-700 to-neutral-800`}>
          {session && <Navigation />}
          <MainPanel>{children}</MainPanel>
        </Container>
      </body>
    </html>
  );
}
